

function [E,g,H] = myAffineObjective3DwithMask(p,I,J,seg,varargin)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% Objective function for 3D Affine Transform  %%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% inputs - p,I,J,seg                                                    %%
%% optional - dJ/dy,dJ/dx,dJ/dz                                          %%
%% p - 12 x 1 parameter vector                                           %%
%% I - fixed image                                                       %%
%% J - moving image                                                      %%
%% seg - segmetation of fixed image                                      %%
%% dJ/dy - gradient of moving image in y direction                       %%
%% dJ/dx - gradient of moving image in x direction                       %%
%% dJ/dz - gradient of moving image in z direction                       %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% outputs - E,g                                                         %%
%% E - value of the objective function                                   %%
%% g - gradient of the objective function                                %%
%% H - Hessian of the objective function                                 %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% check if number of arguments are between 3 and 6 
minarg = 4;
maxarg = 7;
narginchk(minarg, maxarg);
    
A = reshape(p(1:9),[3,3]);
b = p(10:12);

% coordinates of voxels in the mask    
[l, m, n] = ind2sub(size(seg),find(seg ~= 0));

[u, v, w] = ndgrid(min(l):max(l), min(m):max(m), min(n):max(n));

S = transpose([u(:) v(:) w(:)]);
b_rep = repmat(b, 1, numel(u));

% transformation parameters
phi = A*S + b_rep;

phi_x = phi(1,:);
phi_y = phi(2,:);
phi_z = phi(3,:);

phi_x = reshape(phi_x, size(u));
phi_y = reshape(phi_y, size(u));
phi_z = reshape(phi_z, size(u));

% resample moving image
J_t = interpn(J,phi_x,phi_y,phi_z,'linear',0);

% extract points in fixed image relevant to mask
I_i = interpn(I,u,v,w,'linear',0);

% compute the difference image
diff_image = I_i - J_t;

% compute the value of the objective function
E = sum(sum(sum(diff_image.^2)));

% compute gradient of resampled image
if (nargin == 7 && ~isempty(varargin{1}) && ~isempty(varargin{2}) && ~isempty(varargin{3}))
    dJdy = varargin{1};
    dJdx = varargin{2};
    dJdz = varargin{3};
else
    [dJdy, dJdx, dJdz] = gradient(J);
end

dJdx_phi = interpn(dJdx,phi_x,phi_y,phi_z,'linear',0);
dJdy_phi = interpn(dJdy,phi_x,phi_y,phi_z,'linear',0);
dJdz_phi = interpn(dJdz,phi_x,phi_y,phi_z,'linear',0);

% compute partial derivative of E w.r.t. p
g = [-2*sum(sum(sum(diff_image.*dJdx_phi.*u)));
    -2*sum(sum(sum(diff_image.*dJdy_phi.*u)));
    -2*sum(sum(sum(diff_image.*dJdz_phi.*u)));
    -2*sum(sum(sum(diff_image.*dJdx_phi.*v)));
    -2*sum(sum(sum(diff_image.*dJdy_phi.*v)));
    -2*sum(sum(sum(diff_image.*dJdz_phi.*v)));
    -2*sum(sum(sum(diff_image.*dJdx_phi.*w)));
    -2*sum(sum(sum(diff_image.*dJdy_phi.*w)));
    -2*sum(sum(sum(diff_image.*dJdz_phi.*w)));
    -2*sum(sum(sum(diff_image.*dJdx_phi)));
    -2*sum(sum(sum(diff_image.*dJdy_phi)));
    -2*sum(sum(sum(diff_image.*dJdz_phi)))];

% compute 2nd order partial derivatives
[Jxy, Jxx, Jxz] = gradient(dJdx);
[Jyy, Jyx, Jyz] = gradient(dJdy);
[Jzy, Jzx, Jzz] = gradient(dJdz);

Jxx_phi = interpn(Jxx,phi_x,phi_y,phi_z,'linear',0);
Jxy_phi = interpn(Jxy,phi_x,phi_y,phi_z,'linear',0);
Jxz_phi = interpn(Jxz,phi_x,phi_y,phi_z,'linear',0);
Jyx_phi = interpn(Jyx,phi_x,phi_y,phi_z,'linear',0);
Jyy_phi = interpn(Jyy,phi_x,phi_y,phi_z,'linear',0);
Jyz_phi = interpn(Jyz,phi_x,phi_y,phi_z,'linear',0);
Jzx_phi = interpn(Jzx,phi_x,phi_y,phi_z,'linear',0);
Jzy_phi = interpn(Jzy,phi_x,phi_y,phi_z,'linear',0);
Jzz_phi = interpn(Jzz,phi_x,phi_y,phi_z,'linear',0);

% compute Hessian of E w.r.t. p
H = zeros(12,12);

H(1,:) = [-2*(sum(sum(sum(-(dJdx_phi.*u).^2 + diff_image.*Jxx_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdx_phi.*u + diff_image.*Jxy_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdx_phi.*u + diff_image.*Jxz_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdx_phi.*u + diff_image.*Jxx_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdx_phi.*u + diff_image.*Jxy_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdx_phi.*u + diff_image.*Jxz_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdx_phi.*u + diff_image.*Jxx_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdx_phi.*u + diff_image.*Jxy_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdx_phi.*u + diff_image.*Jxz_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdx_phi.*u + diff_image.*Jxx_phi.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdx_phi.*u + diff_image.*Jxy_phi.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdx_phi.*u + diff_image.*Jxz_phi.*u))))];

H(2,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdy_phi.*u + diff_image.*Jyx_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-(dJdy_phi.*u).^2 + diff_image.*Jyy_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdy_phi.*u + diff_image.*Jyz_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdy_phi.*u + diff_image.*Jyx_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdy_phi.*u + diff_image.*Jyy_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdy_phi.*u + diff_image.*Jyz_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdy_phi.*u + diff_image.*Jyx_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdy_phi.*u + diff_image.*Jyy_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdy_phi.*u + diff_image.*Jyz_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdy_phi.*u + diff_image.*Jyx_phi.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdy_phi.*u + diff_image.*Jyy_phi.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdy_phi.*u + diff_image.*Jyz_phi.*u))))];

H(3,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdz_phi.*u + diff_image.*Jzx_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdz_phi.*u + diff_image.*Jzy_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-(dJdz_phi.*u).^2 + diff_image.*Jzz_phi.*(u.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdz_phi.*u + diff_image.*Jzx_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdz_phi.*u + diff_image.*Jzy_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdz_phi.*u + diff_image.*Jzz_phi.*u.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdz_phi.*u + diff_image.*Jzx_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdz_phi.*u + diff_image.*Jzy_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdz_phi.*u + diff_image.*Jzz_phi.*u.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdz_phi.*u + diff_image.*Jzx_phi.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdz_phi.*u + diff_image.*Jzy_phi.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdz_phi.*u + diff_image.*Jzz_phi.*u))))];

H(4,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdx_phi.*v + diff_image.*Jxx_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdx_phi.*v + diff_image.*Jxy_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdx_phi.*v + diff_image.*Jxz_phi.*v.*u)))),...
    -2*(sum(sum(sum(-(dJdx_phi.*v).^2 + diff_image.*Jxx_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdx_phi.*v + diff_image.*Jxy_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdx_phi.*v + diff_image.*Jxz_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdx_phi.*v + diff_image.*Jxx_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdx_phi.*v + diff_image.*Jxy_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdx_phi.*v + diff_image.*Jxz_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdx_phi.*v + diff_image.*Jxx_phi.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdx_phi.*v + diff_image.*Jxy_phi.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdx_phi.*v + diff_image.*Jxz_phi.*v))))];

H(5,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdy_phi.*v + diff_image.*Jyx_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdy_phi.*v + diff_image.*Jyy_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdy_phi.*v + diff_image.*Jyz_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdy_phi.*v + diff_image.*Jyx_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-(dJdy_phi.*v).^2 + diff_image.*Jyy_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdy_phi.*v + diff_image.*Jyz_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdy_phi.*v + diff_image.*Jyx_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdy_phi.*v + diff_image.*Jyy_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdy_phi.*v + diff_image.*Jyz_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdy_phi.*v + diff_image.*Jyx_phi.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdy_phi.*v + diff_image.*Jyy_phi.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdy_phi.*v + diff_image.*Jyz_phi.*v))))];

H(6,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdz_phi.*v + diff_image.*Jzx_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdz_phi.*v + diff_image.*Jzy_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdz_phi.*v + diff_image.*Jzz_phi.*v.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdz_phi.*v + diff_image.*Jzx_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdz_phi.*v + diff_image.*Jzy_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdz_phi.*v + diff_image.*Jzz_phi.*(v.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdz_phi.*v + diff_image.*Jzx_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdz_phi.*v + diff_image.*Jzy_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdz_phi.*v + diff_image.*Jzz_phi.*v.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdz_phi.*v + diff_image.*Jzx_phi.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdz_phi.*v + diff_image.*Jzy_phi.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdz_phi.*v + diff_image.*Jzz_phi.*v))))];

H(7,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdx_phi.*w + diff_image.*Jxx_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdx_phi.*w + diff_image.*Jxy_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdx_phi.*w + diff_image.*Jxz_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdx_phi.*w + diff_image.*Jxx_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdx_phi.*w + diff_image.*Jxy_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdx_phi.*w + diff_image.*Jxz_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdx_phi.*w + diff_image.*Jxx_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdx_phi.*w + diff_image.*Jxy_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdx_phi.*w + diff_image.*Jxz_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdx_phi.*w + diff_image.*Jxx_phi.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdx_phi.*w + diff_image.*Jxy_phi.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdx_phi.*w + diff_image.*Jxz_phi.*w))))];

H(8,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdy_phi.*w + diff_image.*Jyx_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdy_phi.*w + diff_image.*Jyy_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdy_phi.*w + diff_image.*Jyz_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdy_phi.*w + diff_image.*Jyx_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdy_phi.*w + diff_image.*Jyy_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdy_phi.*w + diff_image.*Jyz_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdy_phi.*w + diff_image.*Jyx_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdy_phi.*w + diff_image.*Jyy_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdy_phi.*w + diff_image.*Jyz_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdy_phi.*w + diff_image.*Jyx_phi.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdy_phi.*w + diff_image.*Jyy_phi.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdy_phi.*w + diff_image.*Jyz_phi.*w))))];

H(9,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdz_phi.*w + diff_image.*Jzx_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdz_phi.*w + diff_image.*Jzy_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdz_phi.*w + diff_image.*Jzz_phi.*w.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdz_phi.*w + diff_image.*Jzx_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdz_phi.*w + diff_image.*Jzy_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdz_phi.*w + diff_image.*Jzz_phi.*w.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdz_phi.*w + diff_image.*Jzx_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdz_phi.*w + diff_image.*Jzy_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdz_phi.*w + diff_image.*Jzz_phi.*(w.^2))))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdz_phi.*w + diff_image.*Jzx_phi.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdz_phi.*w + diff_image.*Jzy_phi.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdz_phi.*w + diff_image.*Jzz_phi.*w))))];

H(10,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdx_phi + diff_image.*Jxx_phi.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdx_phi + diff_image.*Jxy_phi.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdx_phi + diff_image.*Jxz_phi.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdx_phi + diff_image.*Jxx_phi.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdx_phi + diff_image.*Jxy_phi.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdx_phi + diff_image.*Jxz_phi.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdx_phi + diff_image.*Jxx_phi.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdx_phi + diff_image.*Jxy_phi.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdx_phi + diff_image.*Jxz_phi.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdx_phi + diff_image.*Jxx_phi)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdx_phi + diff_image.*Jxy_phi)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdx_phi + diff_image.*Jxz_phi))))];

H(11,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdy_phi + diff_image.*Jyx_phi.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdy_phi + diff_image.*Jyy_phi.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdy_phi + diff_image.*Jyz_phi.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdy_phi + diff_image.*Jyx_phi.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdy_phi + diff_image.*Jyy_phi.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdy_phi + diff_image.*Jyz_phi.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdy_phi + diff_image.*Jyx_phi.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdy_phi + diff_image.*Jyy_phi.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdy_phi + diff_image.*Jyz_phi.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdy_phi + diff_image.*Jyx_phi)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdy_phi + diff_image.*Jyy_phi)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdy_phi + diff_image.*Jyz_phi))))];

H(12,:) = [-2*(sum(sum(sum(-dJdx_phi.*u.*dJdz_phi + diff_image.*Jzx_phi.*u)))),...
    -2*(sum(sum(sum(-dJdy_phi.*u.*dJdz_phi + diff_image.*Jzy_phi.*u)))),...
    -2*(sum(sum(sum(-dJdz_phi.*u.*dJdz_phi + diff_image.*Jzz_phi.*u)))),...
    -2*(sum(sum(sum(-dJdx_phi.*v.*dJdz_phi + diff_image.*Jzx_phi.*v)))),...
    -2*(sum(sum(sum(-dJdy_phi.*v.*dJdz_phi + diff_image.*Jzy_phi.*v)))),...
    -2*(sum(sum(sum(-dJdz_phi.*v.*dJdz_phi + diff_image.*Jzz_phi.*v)))),...
    -2*(sum(sum(sum(-dJdx_phi.*w.*dJdz_phi + diff_image.*Jzx_phi.*w)))),...
    -2*(sum(sum(sum(-dJdy_phi.*w.*dJdz_phi + diff_image.*Jzy_phi.*w)))),...
    -2*(sum(sum(sum(-dJdz_phi.*w.*dJdz_phi + diff_image.*Jzz_phi.*w)))),...
    -2*(sum(sum(sum(-dJdx_phi.*dJdz_phi + diff_image.*Jzx_phi)))),...
    -2*(sum(sum(sum(-dJdy_phi.*dJdz_phi + diff_image.*Jzy_phi)))),...
    -2*(sum(sum(sum(-dJdz_phi.*dJdz_phi + diff_image.*Jzz_phi))))];

end